---
- name: Check connect
  hosts: b1-distsw01
  tasks:
    - name: Test connectivity (Ansible_core)
      ios_facts:
        provider: "{{ creds_core_ssh }}"

    - name: Test connectivity (NAPALM)
      napalm_get_facts:
        provider: "{{ creds_napalm }}"


