loopback_ip: 10.199.18.6
management_ip: 172.18.31.6

def_gateway: 172.16.2.25

uplinks:
  - desc: Naar b1-distsw01
    my_port: Ethernet0/0
    my_ip: 172.18.2.26/30
    remote_port: Ethernet3/2
    remote_ip: 172.18.2.25/30
