---
- name: Get all IOS models on HQ and b1-r1
  hosts: hq:b1-r1
  tasks:
    - ios_command:
        provider: "{{ creds_core_ssh }}"
        commands: show ip int brief
      register: output

    - debug:
        msg: "{{ output['stdout_lines'] }}"
