---
- name: Check connect
  hosts: b1-distsw01
  tasks:
    - name: Test connectivity (Ansible_core)
      ios_facts:
        provider: "{{ creds_core_ssh }}"

    - name: Test connectivity (NAPALM)
      napalm_get_facts:
        provider: "{{ creds_napalm }}"

    - name: Install VLANs
      napalm_install_config:
        provider: "{{ creds_napalm }}"
        config_file: "CFGS/{{ inventory_hostname }}-vlans.txt"
        commit_changes: False
        replace_config: False
        diff_file: "CFGS/{{ inventory_hostname }}-vlans.diff"
      register: diff_output
