---
- name: Aanmaken device configs voor Routers Branche1
  hosts: routers-branche1
  tasks:
    - name: Generate Full template
      template:
        src: templates/baseline-router.j2
        dest: "CFGS/{{ inventory_hostname}}.baseline.confg"
      tags: template

- name: Aanmaken device configs voor switches Branche1
  hosts: distsw-branche1:accsw-branche1
  tasks:
    - name: Generate Full template
      template:
        src: templates/baseline-switch.j2
        dest: "CFGS/{{ inventory_hostname}}.baseline.confg"
      tags: template


