---
- name: Setup LLDP
  hosts: hq
  tasks:
    - name: Enable LLDP on HQ devices
      ios_config: 
        provider: "{{ creds_core_ssh }}"
        commands:
        - lldp run
   
    - name: Wait for LLDP to start
      pause: seconds=15 prompt="Waiting for LLDP to start"
      when: wait_flag is defined

    - name: Check LLDP neighbour
      napalm_get_facts:
        provider: "{{ creds_napalm }}"
        filter: "lldp_neighbors"
      register: lldp_output
      tags: [ lldp ]

    - name: Check LLDP list
      debug:
        msg: "{{ lldp_output.ansible_facts.napalm_lldp_neighbors }}"

#    - name: Check LLDP list - smaller
#      debug:
#        msg: "{{ napalm_lldp_neighbors()[1] }}"


#    - name: Set LLDP as string
#      debug:
#        msg: "{{ lookup('template', './templates/convert_lldp_nb.j2') }}"

