---
- hosts: routers
  gather_facts: false
  connection: local
  tasks:
  - name: Generate global configuration
    template: src=templates/routers_full_config_all.j2 dest=./CFGS/output/{{inventory_hostname}}.full    
