---
- name: Push config
  hosts: hq
  tasks:
    - name: add SNMP server to YaWorks NMS
      ios_config:
        provider: "{{ creds_core_ssh }}"
        lines:
          - snmp-server community yaworks-RO RO
          - snmp-server trap-source Loopback0
          - snmp-server contact YaWorks-admin
          - snmp-server host 172.16.0.10 yaworks-snmp 

