---
- hosts: hq-distsw01
  tasks:
  - name: Get LLDP neighbors
    napalm_get_facts:
      provider: "{{ creds_napalm }}"
      filter:
      - lldp_neighbors
    register: nb_list

  - debug: 
      var: {{ nb_list }}
