---
- name: Check connectivity hq-distsw01 and hq-r1
  hosts: hq-distsw01:hq-r1
  tasks:
    - name: Test connectivity (Ansible_core)
      ios_facts:
        provider: "{{ creds_core_ssh }}"

    - name: Test connectivity (NAPALM)
      napalm_get_facts:
        provider: "{{ creds_napalm }}"


