---
- name: Set logging
  hosts: hq
  tasks:
    - name: Logging to YaWorks NMS
      ios_logging:
        provider: "{{ creds_core_ssh }}"
        dest: host
        name: 172.16.0.5
        state: present

    - name: configure console logging level and facility
      ios_logging:
        provider: "{{ creds_core_ssh }}"
        dest: console
        facility: local7
        level: debugging
        state: present

    - name: enable logging to all
      ios_logging:
        provider: "{{ creds_core_ssh }}"
        dest : on

    - name: configure buffer size
      ios_logging:
        provider: "{{ creds_core_ssh }}"
        dest: buffered
        size: 5000
