loopback_ip: 10.199.10.3
management_ip: 172.10.30.3

vlans:
  11: HQ-R1
  12: HQ-R2
  100: Frontend-DMZ
  200: Backend
  300: Management
  999: DISABELD

vlan_ips:
  1: 10.0.10.10 255.255.255.0
  11: 10.0.11.1 255.255.255.248
  12: 10.0.11.9 255.255.255.248


uplinks:
  - desc: Naar Router 1
    my_port: Ethernet0/0
    my_ip: 10.0.11.1/30
    remote_port: Ethernet1/0
    remote_ip: 10.0.11.2/3
  - desc: Naar Router 2
    my_port: Ethernet0/1
    my_ip: 10.0.11.9/30
    remote_port: Ethernet1/0
    remote_ip: 10.0.11.10/3
  - desc: Naar Management net
    my_port: Ethernet1/0
    my_ip: 172.16.0.254/24
    remote_port: Netwerk VMware
    remote_ip: 172.16.0.0/24

